[IG]
ig = fsh-generated/resources/ImplementationGuide-nl.gis.fhir.json
template = fhir2.base.template#current
i18n-default-lang = en-US
#For more template examples: https://raw.githubusercontent.com/FHIR/sample-ig/master/ig.ini