site_name: VWS - Programma Generieke Functies

site_url: https://minvws.github.io/generiekefuncties-docs/

repo_url: https://github.com/minvws/generiekefuncties-docs
edit_uri: edit/main/docs/

nav:
  - Overzicht: index.md
  - Handleiding Github: handleidingen/handleiding frequent gebruiker.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

extra_css:
  - assets/extra.css

theme:
  name: material
  language: nl
  features:
    - content.action.view
    - content.action.edit
