site_name: VWS - Programma Generieke Functies

site_url: https://minvws.github.io/generiekefuncties-docs/

repo_url: https://github.com/minvws/generiekefuncties-docs
edit_uri: edit/main/docs/

nav:
  - Overzicht: index.md
  - Handleiding Github:
      - Indeling van de informatie: handleidingen/de-weg-vinden.md
      - Github introductie: handleidingen/github-intro.md
      - Nieuw document toevoegen: handleidingen/nieuw-document.md
      - Reviewen van wijzigingen: handleidingen/reviewen.md
      - Commentaar op requirements: handleidingen/handleiding commentaar plaatsen.md
  - Architectuur proces: architectuur-proces.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

extra_css:
  - assets/extra.css

theme:
  name: material
  language: nl
  features:
    - content.action.view
    - content.action.edit
  palette:
    primary: custom
